'use strict';
window.NETOPIER = {
  version: 'exploration-2026-09-09-v1',
  fixtureVersion: 'editorial-demo-v1',
  stories: [
    {id:'peniaze',title:'Verejné peniaze pod lupou.',short:'Verejné peniaze',category:'Slovensko',time:'09:42',minutes:4,image:'bratislava-river.jpg',region:'Bratislava',intro:'Čo prezradia zmluvy, rozpočty a ich súvislosti. A čo sa z jedného titulku nikdy nedozvieme.',change:'V modelovom prípade pribudol dodatok k zmluve. Mení termín plnenia, no samotný dokument nevysvetľuje dôvod zmeny.',why:'Sledovať verejné peniaze znamená spojiť rozhodnutie, zmluvu a skutočný výsledok. Až táto postupnosť umožňuje pýtať sa na zodpovednosť.',unknown:'Bez pôvodnej zmluvy, vysvetlenia obstarávateľa a údajov o plnení nemožno hodnotiť primeranosť dodatku.',sources:[['Centrálny register zmlúv','https://www.crz.gov.sk/'],['Úrad pre verejné obstarávanie','https://www.uvo.gov.sk/']],coverage:[1,1,0,1,0]},
    {id:'mesto',title:'Keď sa mesto mení rýchlejšie než plán.',short:'Budúcnosť miest',category:'Slovensko',time:'09:18',minutes:5,image:'bratislava-dusk.jpg',region:'Bratislava',intro:'Bývanie, doprava a verejný priestor patria do jedného príbehu. Na mape ich vidíme spolu.',change:'Modelová úprava plánu pridáva bývanie k dopravnému uzlu. V návrhu sa otvára otázka kapacity škôl a ulíc.',why:'Nová štvrť mení každodenný život aj ľuďom, ktorí sa do nej nikdy nenasťahujú.',unknown:'Ukážka nepredstavuje konkrétny schválený projekt. Potrebovali by sme platný plán a jeho záväzné stanoviská.',sources:[['Bratislava','https://bratislava.sk/'],['Metropolitný inštitút Bratislavy','https://mib.sk/']],coverage:[1,0,1,1,0]},
    {id:'energia',title:'Energia a cena rozhodnutí.',short:'Energia',category:'Ekonomika',time:'08:56',minutes:3,image:'bratislava-dusk.jpg',region:'Brusel',intro:'Za účtom za elektrinu je dlhší reťazec rozhodnutí, než naznačuje konečná suma.',change:'Modelový scenár porovnáva veľkoobchodnú cenu, sieťové náklady a regulovanú časť účtu.',why:'Pohyb jednej položky sa neprenáša automaticky do celej platby domácnosti. Rozklad vysvetľuje, kde vzniká rozdiel.',unknown:'Ukážkové porovnanie neobsahuje aktuálne tarify ani odporúčanie dodávateľa.',sources:[['ÚRSO','https://www.urso.gov.sk/'],['Eurostat','https://ec.europa.eu/eurostat/']],coverage:[0,1,1,0,1]},
    {id:'priestor',title:'Kto rozhoduje o verejnom priestore?',short:'Verejný priestor',category:'Slovensko',time:'08:31',minutes:6,image:'bratislava-river.jpg',region:'Košice',intro:'Miesto patrí všetkým. Rozhodnutie má svojho autora, dokument aj dátum.',change:'Fiktívny prípad sleduje návrh úpravy námestia od prvého zadania po pripomienky obyvateľov.',why:'Dobrá diskusia sa začína tým, že vieme, o čom a v ktorej fáze sa ešte dá rozhodnúť.',unknown:'Vizualizácia projektu sama osebe nepreukazuje stavebné povolenie ani zabezpečené financovanie.',sources:[['Slov-Lex','https://www.slov-lex.sk/'],['Úrad pre verejné obstarávanie','https://www.uvo.gov.sk/']],coverage:[1,0,0,1,1]},
    {id:'europa',title:'Európa medzi zámerom a výsledkom.',short:'Európa',category:'Svet',time:'08:12',minutes:4,image:'bratislava-river.jpg',region:'Brusel',intro:'Dohoda, návrh a platné pravidlo sú tri rôzne momenty. Ich poradie mení celý príbeh.',change:'Ukážka oddeľuje politickú dohodu od formálneho prijatia a neskoršej účinnosti.',why:'Rozdiel medzi návrhom a platným pravidlom určuje, čo sa pre človeka skutočne mení.',unknown:'Nie je to správa o konkrétnom dnešnom rokovaní.',sources:[['Rada EÚ','https://www.consilium.europa.eu/'],['EUR-Lex','https://eur-lex.europa.eu/']],coverage:[1,1,1,1,0]},
    {id:'ai',title:'Keď za nás začnú konať algoritmy.',short:'Technológie a moc',category:'Technológie',time:'07:48',minutes:5,image:'bratislava-dusk.jpg',region:'Brusel',intro:'Automatizácia presúva hranicu medzi odporúčaním a rozhodnutím. Zodpovednosť pri tom nezmizne.',change:'Modelová služba prechádza od návrhov k vykonávaniu úloh. Rozhranie musí zreteľne ukázať rozsah jej oprávnení.',why:'Schopnosť vykonať akciu nie je to isté ako súhlas používateľa s jej vykonaním.',unknown:'Ukážka nehodnotí konkrétny model, firmu ani zavedený systém.',sources:[['Európska komisia — digitálna stratégia','https://digital-strategy.ec.europa.eu/']],coverage:[0,1,1,1,1]},
    {id:'media',title:'Päť titulkov. Jedna udalosť.',short:'Médiá pod lupou',category:'Technológie',time:'07:25',minutes:4,image:'bratislava-river.jpg',region:'Bratislava',intro:'Čo sa pri prechode od pôvodného dokumentu k titulku zvýrazní, stratí alebo zmení?',change:'Päť modelových redakcií opisuje rovnaký fiktívny dodatok. Každá vyberá iný aspekt.',why:'Porovnanie rámcov pomáha rozlíšiť rozdiel v dôraze od vecného rozporu.',unknown:'Všetky titulky aj údaje o pokrytí sú modelové. Žiadnej skutočnej redakcii sa nepripisujú.',sources:[['Pôvodný dokument — referenčný register','https://www.crz.gov.sk/']],coverage:[1,1,1,1,1]},
    {id:'data',title:'Číslo potrebuje svoj menovateľ.',short:'Dáta a súvislosti',category:'Ekonomika',time:'07:04',minutes:3,image:'bratislava-dusk.jpg',region:'Košice',intro:'Rekord môže znamenať rast, zmenu metodiky aj väčšiu vzorku. Kontext rozhoduje.',change:'Ukážkové porovnanie mení pohľad z absolútneho počtu na počet vzhľadom na veľkosť populácie.',why:'Dve zdanlivo protichodné čísla môžu opisovať odlišné otázky.',unknown:'Zobrazené poradie je súčasťou dizajnovej ukážky, nie štatistický záver.',sources:[['Štatistický úrad SR','https://slovak.statistics.sk/'],['Eurostat','https://ec.europa.eu/eurostat/']],coverage:[1,0,1,0,1]},
    {id:'voda',title:'Voda prekračuje hranice okresov.',short:'Krajina',category:'Svet',time:'06:42',minutes:5,image:'bratislava-river.jpg',region:'Košice',intro:'Na administratívnej mape je rieka čiara. V krajine spája rozhodnutia proti prúdu aj pod ním.',change:'Modelový prehľad spája hospodárenie s vodou, zastavané plochy a plánovanie krajiny.',why:'Rozhodnutie jednej samosprávy môže ovplyvniť susednú. Mapa má ukázať túto súvislosť.',unknown:'Schéma neobsahuje aktuálne výstrahy, hydrologické merania ani predpoveď.',sources:[['SHMÚ','https://www.shmu.sk/']],coverage:[0,0,1,1,1]}
  ],
  families:[
    {id:'edition',name:'Vydanie',mode:'Redakčný prehľad',headline:'Verejné peniaze pod lupou.',description:'Veľká typografia, presná hierarchia a noviny, ktoré dýchajú.',seed:'01',font:'Newsreader',bg:'#faf9f5',ink:'#252622',accent:'#a72f30',names:['Prvé vydanie','Veľký formát','Pohľad redakcie','Večerné noviny','Vydanie × Priezor'],hypotheses:['Trojstĺpec s dominantným článkom a časovým okrajom.','Panoramatický titulný pás pred štvorstĺpcovým obsahom.','Titulný článok stojí medzi dvoma úzkymi redakčnými stĺpcami.','Inverzná kompozícia začína chronologickým prehľadom.','Novinový formát nesie porovnávaciu maticu zdrojov.']},
    {id:'wire',name:'Signál',mode:'Prúd udalostí',headline:'Svet sa mení. Sleduj súvislosti.',description:'Čas je navigácia. Aktualizácie majú miesto aj kontext.',seed:'02',font:'Manrope',bg:'#12262b',ink:'#f2f4e9',accent:'#d4e575',names:['Nočný signál','Dispečing','Priebežne','Časové pásmo','Signál × Ranník'],hypotheses:['Časový prúd vedľa pevného úvodu a sledovaných tém.','Rozdelená plocha: zoznam vľavo, otvorená udalosť vpravo.','Jedna široká typografická os, detaily po rozbalení.','Prúd rozdelený do ranných a dopoludňajších intervalov.','K časovému prúdu pribúda konečný výber troch správ.']},
    {id:'prism',name:'Priezor',mode:'Porovnanie zdrojov',headline:'Jedna udalosť. Viac pohľadov.',description:'Zdroje vedľa seba. Rozdiely, ktoré sa dajú prečítať.',seed:'03',font:'Newsreader',bg:'#f5efe5',ink:'#302b24',accent:'#aa451b',names:['Vedľa seba','Mriežka pokrytia','Tri otázky','Dvojitý pohľad','Priezor × Spis'],hypotheses:['Tri paralelné stĺpce pôvod, pokrytie a neistota.','Matica udalostí a modelových redakcií je prvým vstupom.','Čitateľ prechádza tri otázky cez postupné odhalenie.','Dve modelové formulácie stoja vedľa pôvodnej otázky.','Porovnanie dopĺňa súvislý rozbor s marginálnymi poznámkami.']},
    {id:'magazine',name:'Panoráma',mode:'Obrazový magazín',headline:'Mesto nie je kulisa.',description:'Fotografia vedie pohľad. Typografia nesie význam.',seed:'04',font:'Barlow Condensed',bg:'#f9faf7',ink:'#163898',accent:'#163898',names:['Modrá hodina','Veľký obraz','Dvojstrana','Kultúrny rez','Panoráma × Atlas'],hypotheses:['Asymetrická obálka spája veľkú fotografiu s úzkym stĺpcom.','Celostránkový obraz stojí pod rozsiahlym redakčným titulkom.','Dva rovnocenné obrazové príbehy tvoria titulnú dvojstranu.','Vertikálne radené obrazové a textové pásy menia rytmus.','Obraz mesta je vstupom do geografického výberu tém.']},
    {id:'atlas',name:'Atlas',mode:'Priestorové súvislosti',headline:'Udalosti majú svoje miesto.',description:'Svet cez miesta a väzby, s rovnocenným textovým vstupom.',seed:'05',font:'Manrope',bg:'#e8eee9',ink:'#173d35',accent:'#a43f22',names:['Mapa súvislostí','Pohľad z regiónu','Dunajská os','Miesta a príbehy','Atlas × Signál'],hypotheses:['Schematická mapa a zoznam udalostí v rovnováhe.','Zoznam regiónov vedie; mapa tvorí kontext v pravom stĺpci.','Mestá sa radia po horizontálnej osi s príbehmi pod nimi.','Veľké miesto dňa predchádza kompaktnému regionálnemu prehľadu.','Geografický filter dopĺňa chronologický prúd.']},
    {id:'index',name:'Register',mode:'Dokumenty a dáta',headline:'Za rozhodnutím zostáva stopa.',description:'Presnosť registra s redakčnou hierarchiou a ľudským čítaním.',seed:'06',font:'Manrope',bg:'#f2f4ee',ink:'#25352d',accent:'#286647',names:['Verejný register','Čo pribudlo','Otvorený záznam','Číselník','Register × Priezor'],hypotheses:['Zoraditeľná tabuľka udalostí tvorí hlavný vstup.','Výpis zmien dokumentov má prednosť pred celými príbehmi.','Register vľavo a otvorený záznam vpravo.','Veľký index tém dopĺňajú typografické číselné odkazy.','Tabuľku dopĺňa porovnanie modelového pokrytia.']},
    {id:'brief',name:'Ranník',mode:'Konečný briefing',headline:'Dobré ráno. Toto stojí za pozornosť.',description:'Päť príbehov, jasný koniec a miesto na vlastné premýšľanie.',seed:'07',font:'Newsreader',bg:'#f2eedf',ink:'#193e32',accent:'#285741',names:['Pokojné ráno','Päť zastavení','Denný list','Jedna po druhej','Ranník × Panoráma'],hypotheses:['Jedna otvorená udalosť s bočným obsahom piatich kapitol.','Päť kompaktných očíslovaných blokov na jednej stránke.','Úzky redakčný list s osobitým rytmom odsekov.','Veľké samostatné kapitoly s ovládaním predchádzajúca a ďalšia.','Konečný briefing sa otvára výraznou fotografickou obálkou.']},
    {id:'poster',name:'Manifest',mode:'Typografická redakcia',headline:'ROZUMIEŤ. SÚVISLOSTIAM.',description:'Verejná téma ako silné typografické gesto. Čitateľnosť ostáva.',seed:'08',font:'Barlow Condensed',bg:'#e3432c',ink:'#201e1a',accent:'#201e1a',names:['Červená plocha','Verejná vec','Typografický zlom','Stĺpce moci','Manifest × Register'],hypotheses:['Rozsiahly dvojriadkový titul stojí vedľa pevného zoznamu.','Plagátový titul prepája obraz a správy v dolnom páse.','Striedanie bielych a červených textových plôch cez celú šírku.','Štyri vysoké typografické stĺpce majú rovnocenný vstup.','Silný typografický úvod prechádza do presnej tabuľky.']},
    {id:'orbit',name:'Súvislosti',mode:'Sieť tém',headline:'Nič sa nedeje osamote.',description:'Vzťahy medzi témami sa stanú navigáciou, nie dekoráciou.',seed:'09',font:'Manrope',bg:'#172641',ink:'#f0eee5',accent:'#a6cddd',names:['Obežná dráha','Tematické ostrovy','Prepojené','Cesta príbehu','Súvislosti × Spis'],hypotheses:['Interaktívna schéma tém vľavo, vybraná téma vpravo.','Päť tematických oblastí s vlastnými prúdmi udalostí.','Dva tematické stĺpce prepája čitateľný most súvislostí.','Príbehy sa radia po explicitnej trase téma, kontext a pôvod.','Sieť vedie do hĺbkového spisu s poznámkami.']},
    {id:'dossier',name:'Spis',mode:'Sústredené čítanie',headline:'Verejné peniaze pod lupou.',description:'Pokoj knihy, poznámky na okraji a presný pôvod informácií.',seed:'10',font:'Newsreader',bg:'#f8f4ee',ink:'#3a2930',accent:'#722e41',names:['Otvorený spis','S okrajmi','Vývoj prípadu','Čitateľňa','Spis × Ranník'],hypotheses:['Trojica obsah, hlavný text a zdrojové poznámky.','Široké marginálie a otvorená typografia dvojstrany.','Chronológia je kostrou rozboru, text dopĺňa každý moment.','Jeden úzky stĺpec s nastavením veľkosti písma.','Stručné zhrnutie preceduje sústredené hlboké čítanie.']}
  ],
  references:[
    ['Ground News','https://ground.news','Udalosť spája viac zdrojov; porovnanie a pokrytie sú priamo v produkte.'],
    ['Minúta po minúte','https://dennikn.sk/minuta','Silná časová os a skenovateľný priebežný feed.'],
    ['Monocle','https://monocle.com','Redakčná hierarchia, obrazový rytmus a kultivovaná typografia.'],
    ['Particle','https://particle.news','Udalosti sumarizované z viacerých článkov a tematická navigácia.'],
    ['Semafor','https://www.semafor.com','Zreteľné rozlíšenie správy, analýzy a pohľadov.'],
    ['Axios','https://www.axios.com/smart-brevity','Stručnosť a viditeľná hierarchia informácie.'],
    ['MAP-Elites — pôvodný výskum','https://arxiv.org/abs/1504.04909','Zachovať kvalitné možnosti naprieč odlišnými vlastnosťami.'],
    ['Preferenčná Bayesovská optimalizácia','https://proceedings.mlr.press/v70/gonzalez17a.html','Možný ďalší krok po získaní skutočných párových preferencií.']
  ]
};
window.NETOPIER.candidates = window.NETOPIER.families.flatMap((family,f) => family.names.map((name,v) => ({
  id:String(f*5+v+1).padStart(2,'0'),family:family.id,familyIndex:f,variant:v,name,mode:family.mode,
  hypothesis:family.hypotheses[v],stage:v===0?'základ':v===4?'kríženie':'štrukturálna vetva',
  parent:v===0?null:String(f*5+1).padStart(2,'0'),donor:v===4?[2,6,9,4,1,2,3,5,9,6][f]:null,
  route:'#/navrh/'+String(f*5+v+1).padStart(2,'0'),fixture:'editorial-demo-v1',
  descriptors:{readingMode:family.mode,composition:family.hypotheses[v],navigation:['sekcie','priestor','zoznam','postupnosť','kombinácia'][v]},
  review:{kind:'model_proxy',status:'awaiting-render-review'}
})));
